---
- name: "Install Datadog Agent with the offical role"
  ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/datadog-agent-official.yaml"
  when:
    - datadog_agent_install_via_official_role

- name: "Install Datadog Agent with the install script"
  ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/datadog-agent-unofficial.yaml"
  when:
    - datadog_agent_install_via_script
